// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlldfohtkqguodstrggz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsbGRmb2h0a3FndW9kc3RyZ2d6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM0MjM0MjksImV4cCI6MjA3ODk5OTQyOX0.0PXx7zmzk_JrTMfV9bqZBoY_t4YXgAaV0UXeWP23IeI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});